### ISSUE TITLE
partialtokensetratio is wrong

### ISSUE THREAD

**Issue by VolkiTheDreamer** [JakeBayer/FuzzySharp#23]
Hi Jake
thanks for this good stuff. but I'd like to state that paritaltokensetratio is wrong. it always shows %100. u better check it out.

**Comment by JakeBayer** [comment]
Yikes, that's no good. Thanks for bringing this to my attention, I'll take a look.

**Comment by JakeBayer** [comment]
Hey Volki,
So this issue was related to a deeper issue where the base scorers (Default and Partial) would return 100 for empty input strings. This propagated up to the PartialTokenSetScorer in that as part of the scoring, it would check the score against the intersection of the token sets and the difference of the token sets (each individually). For these cases, since the intersection was empty, the partial scorer was returning 100, and the the PartialTokenSetScorer was returning 100.

However, one should note that even with the fix, by the nature of partial scoring and token set scoring, if the two input string share even a single token, they will return 100 for their PartialTokenSetScorer score. This particular scorer seems too powerful to me, and I'm not fully convinced of its use in general because the only way to get a non-100 score is when the two strings share 0 tokens, and are thus most likely quite dissimilar. 

That being said, I have left it in as it falls in nicely with the established paradigm of `ComplexScorerA` having a `PartialComplexScorerA` counterpart.

**Comment by JakeBayer** [comment]
Forgot to mention, I bumped up the version a major step from 1.X.X to 2.0.0 because this is a change to the default behavior of every single scorer, and I do not know how many people are relying on the other behavior.

**Comment by VolkiTheDreamer** [comment]
ok, by the way i had tested it with "papa" and "zuzu"(not mentioning an empty string) ant it also resulted in 100%. Today it is 0%, which seems resolved. I don't know what others think but this is fine with me now and to be honest i've recently got into the similarty stuff and trying to find best algorithm and hence library for me. thanks againf for the work.

**Comment by VolkiTheDreamer** [comment]
Jake, using partialtokensetratio, str1="Vadeli Tl Bakiyesi" and str2="vadeli tl bakiyesi" are supposed to return 100 but it gives me 83. And in Python version I can get the 100 though. Can u check it out please
